export const ARTICLE_PER_PAGE = process.env.NEXT_PUBLIC_ARTICLE_PER_PAGE || 10;

const PRODUCTION_DOMAIN = process.env.NEXT_PUBLIC_PRODUCTION_DOMAIN;
const DEVELOPMENT_DOMAIN = process.env.NEXT_PUBLIC_DEVELOPMENT_DOMAIN;

export const DOMAIN =
  process.env.NODE_ENV === "production"
    ? PRODUCTION_DOMAIN
    : DEVELOPMENT_DOMAIN;
